# -*- coding: utf-8 -*-
"""Licenta_Draft.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UoX_AVnLODWPx2s0YqvA56iL61AQgh14

Dataset Proccessing
"""

from google.colab import files
import numpy as np
import io
import pandas as pd

uploaded = files.upload()

dataset = pd.read_csv(io.BytesIO(uploaded['licenta_dataset.csv']))

def deserializeDataset(dataset):
  dataset_array = []
  for index, row in dataset.iterrows():
    syst = row['system'].encode()
    sol = row['solution'].encode()
    out = row['output'].encode()
    dataset_array.append([np.frombuffer(syst.decode('unicode-escape').encode('ISO-8859-1')[2:-1], dtype=np.float64),
                        np.frombuffer(sol.decode('unicode-escape').encode('ISO-8859-1')[2:-1], dtype=np.float64),
                        np.frombuffer(out.decode('unicode-escape').encode('ISO-8859-1')[2:-1], dtype=np.float64)])
  return dataset_array

ml_dataset = deserializeDataset(dataset)

print(ml_dataset[0])

